/**
 * `pyRound1` — the shared 1-decimal rounding step every ctxdiff percentage goes
 * through, and the one place a JS/Python divergence can hide behind a number
 * that looks fine.
 *
 * This file exists because it DID hide there. `toFixed(1)` rounds half away from
 * zero; CPython's `round` rounds half to even. The original implementation
 * argued that a tie at one decimal is never exactly representable as a double —
 * true only of ties whose exact value ends in a lone `5` at the second place.
 * The ties that actually occur end `.25` or `.75`, are exactly `odd/4`, and come
 * straight out of ordinary ctxdiff arithmetic: a 61-token turn against an
 * 80-token window is exactly 76.25%, and a 1-token slice of a 16-token turn is
 * exactly 6.25%. Both printed one digit differently in the two SDKs.
 */
import { describe, it, expect } from "vitest";
import { pyRound1 } from "../src/analyze/pyround.js";

describe("pyRound1", () => {
  it("rounds the exactly-representable ties to EVEN, as CPython does", () => {
    // The two shapes that are exactly `odd/4`. `toFixed(1)` would say 76.3/6.3.
    expect(pyRound1((61 / 80) * 100)).toBe(76.2);
    expect(pyRound1((1 / 16) * 100)).toBe(6.2);
    expect(pyRound1((3 / 16) * 100)).toBe(18.8);
    expect(pyRound1(0.25)).toBe(0.2);
    expect(pyRound1(0.75)).toBe(0.8);
    expect(pyRound1(2.75)).toBe(2.8);
  });

  it("steps the same way on negatives", () => {
    // A growth percentage can be negative; the tie rule must not flip there.
    expect(pyRound1(-(61 / 80) * 100)).toBe(-76.2);
    expect(pyRound1(-0.25)).toBe(-0.2);
    expect(pyRound1(-1.25)).toBe(-1.2);
  });

  it("leaves every non-tie at its uniquely closest 1-decimal value", () => {
    expect(pyRound1((1 / 3) * 100)).toBe(33.3);
    expect(pyRound1((2 / 3) * 100)).toBe(66.7);
    expect(pyRound1(12.5)).toBe(12.5);
    expect(pyRound1(100)).toBe(100);
    expect(pyRound1(0)).toBe(0);
  });

  it("passes non-finite values through rather than inventing a number", () => {
    expect(pyRound1(Infinity)).toBe(Infinity);
    expect(Number.isNaN(pyRound1(NaN))).toBe(true);
  });

  it("keeps -0 negative, the way CPython's round(-0.0, 1) does", () => {
    // The one place `toFixed` loses a sign: `(-0).toFixed(1)` is the string
    // "0.0", so the fallback branch used to return +0 where Python returns -0.0
    // — and `f"{-0.0:.1f}"` writes "-0.0" while `(0).toFixed(1)` writes "0.0",
    // so the two SDKs would print different characters for the same double.
    expect(Object.is(pyRound1(-0), -0)).toBe(true);
    expect(Object.is(pyRound1(0), 0)).toBe(true);
    // Already correct, and must stay so: toFixed keeps the sign here.
    expect(Object.is(pyRound1(-0.04), -0)).toBe(true);
  });

  it("does not take the tie branch where `x * 10` stops being exact", () => {
    // The tie branch multiplies by 10 and calls the result exact. That holds
    // only while the half-integer still fits the 53-bit significand:
    // 2251799813685247.75 IS `odd/4` (so it passes the tie TEST), but
    // `x * 10` rounds to …2476 and the branch would answer …247.5 where CPython
    // says …247.8. The `Number.isSafeInteger(scaled * 2)` guard sends it to
    // `toFixed`, which reads the exact double and agrees with CPython.
    expect(pyRound1(2251799813685247.75)).toBe(2251799813685247.8);
    expect(pyRound1(-2251799813685247.75)).toBe(-2251799813685247.8);
    // ...and the guard must not disturb the ties that ctxdiff actually produces.
    expect(pyRound1(76.25)).toBe(76.2);
  });

  it("agrees with CPython across every percentage a small run can produce", () => {
    // The shape every ctxdiff percentage has: `someInt / someInt * 100`. The
    // expectations below were generated by CPython's `round(x, 1)` and are
    // spot-checked here for the values that are ties; the exhaustive
    // cross-language sweep lives in the conformance suite, which compares the
    // two CLIs' rendered output directly.
    const ties: [number, number, number][] = [
      [1, 16, 6.2],
      [3, 16, 18.8],
      [5, 16, 31.2],
      [7, 16, 43.8],
      [61, 80, 76.2],
      [1, 32, 3.1], // 3.125 — not a tie at 1 decimal, rounds to nearest
    ];
    for (const [n, d, expected] of ties) {
      expect(pyRound1((n / d) * 100), `${n}/${d}`).toBe(expected);
    }
  });
});
